# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PocketServer < Formula
  desc "Persistent encrypted terminal sessions"
  homepage "https://github.com/digitalpine/pocket-server"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DigitalPine/pocket-server/releases/download/v1.0.1/pocket-server_1.0.1_darwin_amd64.tar.gz"
      sha256 "7c2f469777d0e736a2d00cc5870dccd762c2ced339cceeab65cc4ffb0dd18e26"

      def install
        bin.install "pocket-server"
        bin.install "pocket-client"
        bin.install "pocket-terminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DigitalPine/pocket-server/releases/download/v1.0.1/pocket-server_1.0.1_darwin_arm64.tar.gz"
      sha256 "234cf896141660f6084346eaf359e5ecce73c7a219ea24624f0b779a757d5116"

      def install
        bin.install "pocket-server"
        bin.install "pocket-client"
        bin.install "pocket-terminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DigitalPine/pocket-server/releases/download/v1.0.1/pocket-server_1.0.1_linux_amd64.tar.gz"
      sha256 "2300eacb218bcd3fe7272ff0f0a3af1ab28f6c0123d75829702f90cb71405a1a"
      def install
        bin.install "pocket-server"
        bin.install "pocket-client"
        bin.install "pocket-terminal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DigitalPine/pocket-server/releases/download/v1.0.1/pocket-server_1.0.1_linux_arm64.tar.gz"
      sha256 "89a97f95ac7c8c53722eae08a6d9360f19903365fc015169e344e290a85317cd"
      def install
        bin.install "pocket-server"
        bin.install "pocket-client"
        bin.install "pocket-terminal"
      end
    end
  end

  test do
    system bin/"pocket-server", "--version"
    system bin/"pocket-client", "--version"
  end
end
